[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "py-tiltium"
version = "0.1.1"
dependencies = [
    "pyside6",
    "pyserial",
]

[project.scripts]
py-tiltium = "main:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 100

[tool.ruff.format]
quote-style = "double"

[tool.ruff.lint]
select = ["E", "F", "I", "RUF"]
